# Eat Safe, Love

## Notebook Set Up

In [11]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [3]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [4]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [5]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [6]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [21]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)
print("Number of establishments with a hygiene score of 20:", count)

# Display the first document in the results using pprint
print("First document:")
pprint(establishments.find_one(query))

Number of establishments with a hygiene score of 20: 41
First document:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'Latitude': None,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'Longitude': None,
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64b6a570784e60951f60fb0e'),
 'geocode': {'latitude': '50.769705', 'longitude': '0.27694'},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [22]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(list(establishments.find(query)))
# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame:", len(df))
# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
print(df.head(10))

Number of rows in the DataFrame: 41
First 10 rows of the DataFrame:
                        _id   FHRSID  ChangesByServerID  \
0  64b6a570784e60951f60fb0e   110681                  0
1  64b6a570784e60951f60fe8d   612039                  0
2  64b6a571784e60951f610197   730933                  0
3  64b6a571784e60951f610387   172735                  0
4  64b6a571784e60951f610396   172953                  0
5  64b6a571784e60951f610d3d   512854                  0
6  64b6a571784e60951f610f53  1537089                  0
7  64b6a571784e60951f612481   155648                  0
8  64b6a571784e60951f6128cc  1012883                  0
9  64b6a571784e60951f6130d6   644109                  0

  LocalAuthorityBusinessID               BusinessName  \
0                     4029        The Chase Rest Home
1                1970/FOOD                 Brenalwood
2                1698/FOOD              Melrose Hotel
3             PI/000023858              Seaford Pizza
4             PI/000024532              Golden Palace
5            12/00816/BUTH           Ashby's Butchers
6          22/00224/RESTUN  South Sea Express Cuisine
7              EH/00006058              Golden Palace
8         17/00110/MIXED/S             The Tulip Tree
9                    41811                      F & S

                        BusinessType  BusinessTypeID           AddressLine1  \
0                    Caring Premises               5   5-6 Southfields Road
1                    Caring Premises               5              Hall Lane
2  Hotel/bed & breakfast/guest house            7842  53 Marine Parade East
3             Takeaway/sandwich shop            7844          4 High Street
4            Restaurant/Cafe/Canteen               1         5 South Street
5                  Retailers - other            4613   777 Southchurch Road
6            Restaurant/Cafe/Canteen               1    33 Alexandra Street
7             Takeaway/sandwich shop            7844          7 London Road
8            Restaurant/Cafe/Canteen               1          3 The Village
9                  Retailers - other            4613

         AddressLine2 AddressLine3  ...  \
0          Eastbourne  East Sussex  ...
1  Walton-on-the-Naze        Essex  ...
2      Clacton On Sea        Essex  ...
3             Seaford  East Sussex  ...
4             Seaford  East Sussex  ...
5     Southend-On-Sea        Essex  ...
6     Southend-on-sea        Essex  ...
7            Rayleigh        Essex  ...
8       Chiddingstone         KENT  ...
9      81 Southernhay     Basildon  ...

                                              scores SchemeType  \
0  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS
1  {'Hygiene': 20, 'Structural': 15, 'ConfidenceI...       FHRS
2  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS
3  {'Hygiene': 20, 'Structural': 10, 'ConfidenceI...       FHRS
4  {'Hygiene': 20, 'Structural': 10, 'ConfidenceI...       FHRS
5  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS
6  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS
7  {'Hygiene': 20, 'Structural': 15, 'ConfidenceI...       FHRS
8  {'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...       FHRS
9  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...       FHRS

                                             geocode  RightToReply  \
0  {'longitude': '0.27694', 'latitude': '50.769705'}
1  {'longitude': '1.278721', 'latitude': '51.8575...
2  {'longitude': '1.15927', 'latitude': '51.789429'}
3  {'longitude': '0.10202', 'latitude': '50.770885'}
4  {'longitude': '0.101446', 'latitude': '50.7707...
5  {'longitude': '0.736349', 'latitude': '51.5414...
6  {'longitude': '0.7121671', 'latitude': '51.535...
7  {'longitude': '0.602364', 'latitude': '51.5915...
8  {'longitude': '0.146449998021126', 'latitude':...
9  {'longitude': '0.462307', 'latitude': '51.57005'}

      Distance NewRatingPending  \
0  4613.888288            False
1  4617.965824            False
2  4619.656144            False
3  4620.421725            False
4  4620.437179            False
5  4625.565258            False
6  4626.200132            False
7  4632.276890            False
8  4633.934041            False
9  4636.552523            False

                                                meta  \
0  {'dataSource': None, 'extractDate': '0001-01-0...
1  {'dataSource': None, 'extractDate': '0001-01-0...
2  {'dataSource': None, 'extractDate': '0001-01-0...
3  {'dataSource': None, 'extractDate': '0001-01-0...
4  {'dataSource': None, 'extractDate': '0001-01-0...
5  {'dataSource': None, 'extractDate': '0001-01-0...
6  {'dataSource': None, 'extractDate': '0001-01-0...
7  {'dataSource': None, 'extractDate': '0001-01-0...
8  {'dataSource': None, 'extractDate': '0001-01-0...
9  {'dataSource': None, 'extractDate': '0001-01-0...

                                               links Latitude Longitude
0  [{'rel': 'self', 'href': 'https://api.ratings....     None      None
1  [{'rel': 'self', 'href': 'https://api.ratings....     None      None
2  [{'rel': 'self', 'href': 'https://api.ratings....     None      None
3  [{'rel': 'self', 'href': 'https://api.ratings....     None      None
4  [{'rel': 'self', 'href': 'https://api.ratings....     None      None
5  [{'rel': 'self', 'href': 'https://api.ratings....     None      None
6  [{'rel': 'self', 'href': 'https://api.ratings....     None      None
7  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
8  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
9  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None

[10 rows x 30 columns]

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [24]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {"LocalAuthorityName": {"$regex": "London"}, "RatingValue": {"$gte": 4}}

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)
print("Number of establishments in London with a RatingValue greater than or equal to 4:", count)
# Display the first document in the results using pprint
print("First document:")
pprint(establishments.find_one(query))

Number of establishments in London with a RatingValue greater than or equal to 4: 33
First document:
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'Latitude': None,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'Longitude': None,
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64b6a571784e60951f611529'),
 'geocode': {'latitude': '51.369321', 'longitude': '0.508551'},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [25]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(list(establishments.find(query)))

# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame:", len(df))
# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
print(df.head(10))

Number of rows in the DataFrame: 33
First 10 rows of the DataFrame:
                        _id   FHRSID  ChangesByServerID  \
0  64b6a571784e60951f611529   621707                  0
1  64b6a571784e60951f61184d  1130836                  0
2  64b6a571784e60951f61239b   293783                  0
3  64b6a571784e60951f61319c  1315095                  0
4  64b6a571784e60951f61319e   294474                  0
5  64b6a572784e60951f6138a2   294900                  0
6  64b6a572784e60951f6159b2   293756                  0
7  64b6a572784e60951f615d78   878523                  0
8  64b6a572784e60951f615d92   293772                  0
9  64b6a572784e60951f615d93   295107                  0

  LocalAuthorityBusinessID                          BusinessName  \
0             PI/000025307                             Charlie's
1             PI/000034075               Mv City Cruises Erasmus
2             PI/000002614             Benfleet Motor Yacht Club
3             PI/000036464  Coombs Catering t/a The Lock and Key
4             PI/000014647              Tilbury Seafarers Centre
5             PI/000019066                            Mv Valulla
6             PI/000002538                         Tereza Joanne
7             PI/000029844                      Brick Lane Brews
8             PI/000002585         The Nuance Group (UK) Limited
9             PI/000020749                      City Bar & Grill

              BusinessType  BusinessTypeID  \
0  Other catering premises            7841
1  Other catering premises            7841
2  Other catering premises            7841
3  Restaurant/Cafe/Canteen               1
4  Restaurant/Cafe/Canteen               1
5  Other catering premises            7841
6  Other catering premises            7841
7  Restaurant/Cafe/Canteen               1
8        Retailers - other            4613
9  Restaurant/Cafe/Canteen               1

                                        AddressLine1  \
0         Oak Apple Farm Building 103 Sheernes Docks
1                                 Cherry Garden Pier
2                                         Ferry Road
3                                  Leslie Ford House
4                          Tenants Row Tilbury Docks
5  Reeds River Cruises LtdKings ReachRiver Thames...
6  Funcraft UK Ltd King George V Dock Woolwich Ma...
7                       Air side London City Airport
8                  Duty Free Shop Passenger Terminal
9                      London City Airport (Airside)

                           AddressLine2 AddressLine3  ...  \
0                           Sheppy Kent               ...
1      Cherry Garden Street Rotherhithe     Charlton  ...
2                  South Benfleet Essex               ...
3                               Tilbury     Charlton  ...
4                         Tilbury Essex               ...
5                                London               ...
6                                London               ...
7                                London               ...
8  London City AirportRoyal DocksLondon               ...
9                                London               ...

                                              scores SchemeType  \
0  {'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...       FHRS
1  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
2  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
3  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
4  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
5  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
6  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
7  {'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...       FHRS
8  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
9  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS

                                             geocode  RightToReply  \
0  {'longitude': '0.508551', 'latitude': '51.3693...
1  {'longitude': '0.249255999922752', 'latitude':...
2  {'longitude': '0.561954', 'latitude': '51.5438...
3  {'longitude': '0.346336990594864', 'latitude':...
4  {'longitude': '0.346325', 'latitude': '51.4640...
5  {'longitude': '0.287555', 'latitude': '51.5040...
6  {'longitude': '0.069286', 'latitude': '51.5011...
7  {'longitude': '0.048006', 'latitude': '51.5037...
8  {'longitude': '0.047966', 'latitude': '51.5041...
9  {'longitude': '0.0479655750095844', 'latitude'...

      Distance NewRatingPending  \
0  4627.439468            False
1  4627.873179            False
2  4631.968418            False
3  4636.846754            False
4  4636.847650            False
5  4640.460834            False
6  4648.301822            False
7  4649.173485            False
8  4649.188826            False
9  4649.188850            False

                                                meta  \
0  {'dataSource': None, 'extractDate': '0001-01-0...
1  {'dataSource': None, 'extractDate': '0001-01-0...
2  {'dataSource': None, 'extractDate': '0001-01-0...
3  {'dataSource': None, 'extractDate': '0001-01-0...
4  {'dataSource': None, 'extractDate': '0001-01-0...
5  {'dataSource': None, 'extractDate': '0001-01-0...
6  {'dataSource': None, 'extractDate': '0001-01-0...
7  {'dataSource': None, 'extractDate': '0001-01-0...
8  {'dataSource': None, 'extractDate': '0001-01-0...
9  {'dataSource': None, 'extractDate': '0001-01-0...

                                               links Latitude Longitude
0  [{'rel': 'self', 'href': 'https://api.ratings....     None      None
1  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
2  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
3  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
4  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
5  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
6  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
7  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
8  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
9  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None

[10 rows x 30 columns]

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [37]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

query = {
    "RatingValue": 5,
    "Latitude": {"$gte": latitude - degree_search, "$lte": latitude + degree_search},
    "Longitude": {"$gte": longitude - degree_search, "$lte": longitude + degree_search}
}
sort =  [("scores.Hygiene", 1)]

# Print the results
results = establishments.find(query).sort(sort).limit(5)
print("Top 5 establishments with a RatingValue of 5, sorted by lowest hygiene score:")
for doc in results:
    pprint(doc)

Top 5 establishments with a RatingValue of 5, sorted by lowest hygiene score:

In [ ]:
# Convert result to Pandas DataFrame

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [33]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest
pipeline = [
    {"$match": {"scores.Hygiene": 0}},
    {"$group": {"_id": "$LocalAuthorityName", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}}
]

# Print the number of documents in the result
results = establishments.aggregate(pipeline)
print("Number of establishments in each Local Authority area with a hygiene score of 0:")
# Print the first 10 results
for doc in results:
    print(f"{doc['_id']}: {doc['count']}")

Number of establishments in each Local Authority area with a hygiene score of 0:
Thanet: 1130
Greenwich: 882
Maidstone: 713
Newham: 711
Swale: 686
Chelmsford: 680
Medway: 672
Bexley: 607
Southend-On-Sea: 586
Tendring: 542
Colchester: 498
Tunbridge Wells: 491
Folkestone and Hythe: 480
Eastbourne: 478
Hastings: 464
Bromley: 460
Ashford: 427
Havering: 397
Dartford: 383
Braintree: 382
Basildon: 362
Gravesham: 339
Tonbridge and Malling: 325
Thurrock: 313
Barking and Dagenham: 301
Canterbury City: 298
Brentwood: 285
Castle Point: 281
Harlow: 274
Uttlesford: 251
Lewes: 250
Sevenoaks: 223
Maldon: 197
East Hertfordshire: 189
Rochford: 187
Redbridge: 182
Epping Forest: 180
East Suffolk: 159
Waltham Forest: 110
Babergh: 97
Wealden: 93
Rother: 80
Lewisham: 65
Tandridge: 42
City of London Corporation: 28
Ipswich: 21
Tower Hamlets: 9
North Hertfordshire: 6
Mid Sussex: 5
North Norfolk: 1
Kensington and Chelsea: 1
Sunderland: 1
Dorset: 1
Broxbourne: 1
Reading: 1

In [34]:
# Convert the result to a Pandas DataFrame
results = establishments.aggregate(pipeline)
df = pd.DataFrame(list(results))

# Display the number of rows in the DataFrame
print("Number of rows in the DataFrame:", len(df))
# Display the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
print(df.head(10))

Number of rows in the DataFrame: 55
First 10 rows of the DataFrame:
               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542